// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfcVX6SI7EhOHv6cuAuCzV4xR0cVmngg4',
    appId: '1:199804307385:android:d069aa93e39891f28f1868',
    messagingSenderId: '199804307385',
    projectId: 'smartenglish-dd78e',
    storageBucket: 'smartenglish-dd78e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsxFFWG8vx4iney86c2PozqO9ySLjCGmY',
    appId: '1:199804307385:ios:915afde761b2b32f8f1868',
    messagingSenderId: '199804307385',
    projectId: 'smartenglish-dd78e',
    storageBucket: 'smartenglish-dd78e.appspot.com',
    androidClientId: '199804307385-024r3v5p2qu2konjb6j8daqteig8eanm.apps.googleusercontent.com',
    iosClientId: '199804307385-g9jph4qnobg56o2i6mt182o177u70c4e.apps.googleusercontent.com',
    iosBundleId: 'com.example.englishProject',
  );
}
